# -*- coding: utf-8 -*-
"""pp model xgboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zkp-ir3T7Boo7pScxDP-S3Vx4Ezxd8ma
"""

from google.colab import drive
drive.mount('/content/drive')

##BEST SO FAR

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder

# Load data
train = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
test  = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
train = train.dropna(subset=['pitch_type'])

# Define fastballs & features
fastballs = {'FF', 'SI', 'FA', 'FS', 'FC', 'FO'}
for df in (train, test):
    df['is_fastball'] = df['pitch_type'].isin(fastballs).astype(int)
    df['score_diff']  = df['bat_score'] - df['fld_score']
    conditions = [
        (df['balls'] == 3) & (df['strikes'] < 2),
        (df['strikes'] == 2) & (df['balls'] < 3),
        (df['balls'] == 3) & (df['strikes'] == 2),
    ]
    choices = ['hitter', 'pitcher', 'full']
    df['count_bucket'] = np.select(conditions, choices, default='neutral')

categorical = ['p_throws', 'stand', 'count_bucket']
numeric     = ['inning', 'outs_when_up', 'on_1b', 'on_2b', 'on_3b',
               'balls', 'strikes', 'score_diff']
features    = categorical + numeric

# Overall counters
total_correct = 0
total_count   = 0
total_tp      = 0
total_fn      = 0
total_tn      = 0
total_fp      = 0

min_samples = 50

for pitcher in train['player_name'].unique():
    tr = train[train['player_name'] == pitcher]
    te = test[test['player_name']   == pitcher]
    if len(tr) < min_samples or len(te) < min_samples:
        continue

    X_tr = tr[features].copy()
    X_te = te[features].copy()
    y_tr = tr['is_fastball']
    y_te = te['is_fastball']

    # Encode categoricals
    enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    X_tr[categorical] = enc.fit_transform(X_tr[categorical])
    X_te[categorical] = enc.transform(X_te[categorical])

    # Down‐weight fastballs by 20%
    pos = y_tr.sum()
    neg = len(y_tr) - pos
    scale_pos_weight = (pos / neg) * 0.8

    # Train with fixed n_estimators=125
    clf = XGBClassifier(
        n_estimators=125,
        learning_rate=0.01,
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight,
        verbosity=0
    )
    clf.fit(X_tr, y_tr)

    preds = clf.predict(X_te)
    total_correct += (preds == y_te).sum()
    total_count   += len(y_te)

    total_tp += int(((preds == 1) & (y_te == 1)).sum())
    total_fn += int(((preds == 0) & (y_te == 1)).sum())
    total_tn += int(((preds == 0) & (y_te == 0)).sum())
    total_fp += int(((preds == 1) & (y_te == 0)).sum())

# Compute & print metrics
overall_acc  = total_correct / total_count
fastball_acc = total_tp / (total_tp + total_fn)
offspeed_acc = total_tn / (total_tn + total_fp)

print(f"Overall accuracy:    {overall_acc:.3f} ({total_correct}/{total_count})")
print(f"Fastball accuracy:   {fastball_acc:.3%} ({total_tp}/{total_tp + total_fn})")
print(f"Offspeed accuracy:   {offspeed_acc:.3%} ({total_tn}/{total_tn + total_fp})")

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder

# --- 1) Load & preprocess train/test exactly as before ---
train = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
test  = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
train = train.dropna(subset=['pitch_type'])

fastballs = {'FF','SI','FA','FS','FC','FO'}
for df in (train, test):
    df['is_fastball'] = df['pitch_type'].isin(fastballs).astype(int)
    df['score_diff']  = df['bat_score'] - df['fld_score']

# Updated count_bucket rules you wanted:
for df in (train, test):
    conditions = [
        (df['balls']==2)&(df['strikes']==0),
        (df['balls']==3)&(df['strikes']==0),
        (df['balls']==3)&(df['strikes']==1),
        (df['balls']==0)&(df['strikes']==1),
        (df['balls']==0)&(df['strikes']==2),
        (df['balls']==1)&(df['strikes']==2),
        (df['balls']==3)&(df['strikes']==2),
    ]
    choices = ['hitter','hitter','hitter','pitcher','pitcher','pitcher','full']
    df['count_bucket'] = np.select(conditions, choices, default='neutral')

categorical = ['p_throws','stand','count_bucket']
numeric     = ['inning','outs_when_up','on_1b','on_2b','on_3b',
               'balls','strikes','score_diff']
features    = categorical + numeric

# --- 2) Train and store one model+encoder per pitcher ---
min_samples = 50
models       = {}
encoders     = {}

for pitcher in train['player_name'].unique():
    tr = train[ train['player_name']==pitcher ]
    te = test[  test['player_name']==pitcher ]
    if len(tr)<min_samples or len(te)<min_samples:
        continue

    X_tr = tr[features].copy()
    y_tr = tr['is_fastball']

    # fit encoder on this pitcher
    enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    X_tr[categorical] = enc.fit_transform(X_tr[categorical])

    # compute class weight
    pos = y_tr.sum()
    neg = len(y_tr)-pos
    scale_pos_weight = (pos/neg)*0.8

    clf = XGBClassifier(
        n_estimators=125,
        learning_rate=0.01,
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight,
        verbosity=0
    )
    clf.fit(X_tr, y_tr)

    models[pitcher]   = clf
    encoders[pitcher] = enc

# --- 3) Prompt user for a new pitch to score ---
print("Available pitchers:", list(models.keys()))
pname = input("Enter pitcher name exactly: ")

if pname not in models:
    raise ValueError(f"No model found for pitcher '{pname}'")

# collect features from user
inning     = int(input("inning (e.g. 1-9): "))
outs       = int(input("outs_when_up (0,1,2): "))
on_1b      = int(input("runner on first? (1=yes,0=no): "))
on_2b      = int(input("runner on second? (1=yes,0=no): "))
on_3b      = int(input("runner on third? (1=yes,0=no): "))
balls      = int(input("balls count (0-3): "))
strikes    = int(input("strikes count (0-2): "))
bat_score  = int(input("bat_score (team runs): "))
fld_score  = int(input("fld_score (opponent runs): "))
p_throws   = input("pitcher throws (L or R): ").upper()
stand      = input("batter stands (L or R): ").upper()

# build single-row DataFrame
df_new = pd.DataFrame([{
    'inning': inning,
    'outs_when_up': outs,
    'on_1b': on_1b,
    'on_2b': on_2b,
    'on_3b': on_3b,
    'balls': balls,
    'strikes': strikes,
    'score_diff': bat_score - fld_score,
    'p_throws': p_throws,
    'stand': stand,
    # count_bucket via same logic:
    'count_bucket': (
        'hitter' if (balls==2 and strikes==0)
                  or (balls==3 and strikes in [0,1])
        else 'pitcher' if (balls==0 and strikes in [1,2])
                      or (balls==1 and strikes==2)
        else 'full' if (balls==3 and strikes==2)
        else 'neutral'
    )
}])

# encode & predict
enc = encoders[pname]
X_new = df_new[features].copy()
X_new[categorical] = enc.transform(X_new[categorical])

clf = models[pname]
proba = clf.predict_proba(X_new)[0]

print(f"\nPredicted probabilities for {pname}:")
print(f"  Fastball:  {proba[1]:.3f}")
print(f"  Offspeed:  {proba[0]:.3f}")

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder

# Load data (update paths as needed)
train = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
test  = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
train = train.dropna(subset=['pitch_type'])

# Feature engineering
fastballs = {'FF','SI','FA','FS','FC','FO'}
for df in (train, test):
    df['is_fastball'] = df['pitch_type'].isin(fastballs).astype(int)
    df['score_diff']  = df['bat_score'] - df['fld_score']
    # count buckets: hitters = 2-0,3-0,3-1; pitchers = 0-1,0-2,1-2; full = 3-2
    conditions = [
        (df['balls']==2)&(df['strikes']==0),
        (df['balls']==3)&(df['strikes']==0),
        (df['balls']==3)&(df['strikes']==1),
        (df['balls']==0)&(df['strikes']==1),
        (df['balls']==0)&(df['strikes']==2),
        (df['balls']==1)&(df['strikes']==2),
        (df['balls']==3)&(df['strikes']==2),
    ]
    choices = ['hitter','hitter','hitter','pitcher','pitcher','pitcher','full']
    df['count_bucket'] = np.select(conditions, choices, default='neutral')

categorical = ['p_throws','stand','count_bucket']
numeric     = ['inning','outs_when_up','on_1b','on_2b','on_3b',
               'balls','strikes','score_diff']
features    = categorical + numeric

# Train and store model+encoder per pitcher
min_samples = 50
models, encoders = {}, {}

for pitcher in train['player_name'].unique():
    tr = train[train['player_name']==pitcher]
    te = test[test['player_name']==pitcher]
    if len(tr)<min_samples or len(te)<min_samples:
        continue

    X_tr = tr[features].copy()
    y_tr = tr['is_fastball']

    enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    X_tr[categorical] = enc.fit_transform(X_tr[categorical])

    pos = y_tr.sum()
    neg = len(y_tr) - pos
    scale_pos_weight = (pos/neg)*0.8

    clf = XGBClassifier(
        n_estimators=125,
        learning_rate=0.01,
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight,
        verbosity=0
    )
    clf.fit(X_tr, y_tr)

    models[pitcher], encoders[pitcher] = clf, enc

# Evaluate test set: probability scores
all_results = []
for pitcher, clf in models.items():
    enc = encoders[pitcher]
    subset = test[test['player_name']==pitcher].copy()
    if subset.empty:
        continue

    X_t = subset[features].copy()
    X_t[categorical] = enc.transform(X_t[categorical])
    proba = clf.predict_proba(X_t)

    subset['offspeed_prob'] = proba[:,0]
    subset['fastball_prob'] = proba[:,1]
    all_results.append(subset)

combined = pd.concat(all_results)

# Top 10 offspeed‐likely situations
top_off = combined.sort_values('offspeed_prob', ascending=False).head(10)
print("Top 10 Offspeed‐Likely Situations:")
print(top_off[[
    'player_name','inning','outs_when_up','p_throws','stand',
    'count_bucket','balls','strikes','offspeed_prob'
]])

print("\nTop 10 Fastball‐Likely Situations:")
# Top 10 fastball‐likely situations
top_fast = combined.sort_values('fastball_prob', ascending=False).head(10)
print(top_fast[[
    'player_name','inning','outs_when_up','p_throws','stand',
    'count_bucket','balls','strikes','fastball_prob'
]])

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder

# --- load & preprocess exactly as before ---
train = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
test  = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
train = train.dropna(subset=['pitch_type'])

fastballs = {'FF', 'SI', 'FA', 'FS', 'FC', 'FO'}
for df in (train, test):
    df['is_fastball'] = df['pitch_type'].isin(fastballs).astype(int)
    df['score_diff']   = df['bat_score'] - df['fld_score']
    df['count_bucket'] = df.apply(
        lambda r: 'hitter' if (r.balls == 3 and r.strikes < 2)
                  else 'pitcher' if (r.strikes == 2 and r.balls < 3)
                  else 'full'    if (r.balls == 3 and r.strikes == 2)
                  else 'neutral',
        axis=1
    )

categorical = ['p_throws', 'stand', 'count_bucket']
numeric     = ['inning', 'outs_when_up', 'on_1b', 'on_2b', 'on_3b',
               'balls', 'strikes', 'score_diff']
features    = categorical + numeric

# --- define sweep of shrinkage factors (0.5 means down‐weight fastballs by 50%) ---
shrinkages = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.1, 1.2, 1.3, 1.4, 1.5]
min_samples = 50

best_shrink = None
best_acc    = -np.inf
results     = {}

for s in shrinkages:
    total_correct = 0
    total_count   = 0

    for pitcher in train['player_name'].unique():
        tr = train[train['player_name'] == pitcher]
        te = test[test['player_name'] == pitcher]
        if len(tr) < min_samples or len(te) < min_samples:
            continue

        X_tr = tr[features].copy()
        X_te = te[features].copy()
        y_tr = tr['is_fastball']
        y_te = te['is_fastball']

        # compute pos/neg and then shrink
        pos = y_tr.sum()
        neg = len(y_tr) - pos
        base_weight      = pos / neg
        scale_pos_weight = base_weight * s

        # encode categoricals
        enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
        X_tr[categorical] = enc.fit_transform(X_tr[categorical])
        X_te[categorical] = enc.transform(X_te[categorical])

        # train with this shrinkage
        clf = XGBClassifier(
            n_estimators=100,
            learning_rate=0.1,
            use_label_encoder=False,
            eval_metric='logloss',
            scale_pos_weight=scale_pos_weight
        )
        clf.fit(X_tr, y_tr)

        preds = clf.predict(X_te)
        total_correct += (preds == y_te).sum()
        total_count   += len(y_te)

    overall_acc = total_correct / total_count
    results[s] = overall_acc

    if overall_acc > best_acc:
        best_acc    = overall_acc
        best_shrink = s

# --- report ---
print("Shrinkage → overall accuracy")
for s, acc in results.items():
    print(f"  {s:>4}  →  {acc:.3%}")
print()
print(f"Best shrinkage: {best_shrink} (accuracy {best_acc:.3%})")

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import f1_score

# Load data (adjust paths if needed)
train = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
test  = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
train = train.dropna(subset=['pitch_type'])

# Feature engineering
fastballs = {'FF', 'SI', 'FA', 'FS', 'FC', 'FO'}
for df in (train, test):
    df['is_fastball'] = df['pitch_type'].isin(fastballs).astype(int)
    df['score_diff']  = df['bat_score'] - df['fld_score']
    conditions = [
        (df['balls'] == 2) & (df['strikes'] == 0),
        (df['balls'] == 3) & (df['strikes'] == 0),
        (df['balls'] == 3) & (df['strikes'] == 1),
        (df['balls'] == 0) & (df['strikes'] == 1),
        (df['balls'] == 0) & (df['strikes'] == 2),
        (df['balls'] == 1) & (df['strikes'] == 2),
        (df['balls'] == 3) & (df['strikes'] == 2),
    ]
    choices = ['hitter','hitter','hitter','pitcher','pitcher','pitcher','full']
    df['count_bucket'] = np.select(conditions, choices, default='neutral')

categorical = ['p_throws','stand','count_bucket']
numeric     = ['inning','outs_when_up','on_1b','on_2b','on_3b','balls','strikes','score_diff']
features    = categorical + numeric

# Collect true labels and predicted probabilities
all_y     = []
all_proba = []

min_samples = 50
n_estimators = 125
learning_rate = 0.01

for pitcher in train['player_name'].unique():
    tr = train[train['player_name']==pitcher]
    te = test[test['player_name']==pitcher]
    if len(tr)<min_samples or len(te)<min_samples:
        continue

    X_tr = tr[features].copy()
    X_te = te[features].copy()
    y_tr = tr['is_fastball']
    y_te = te['is_fastball']

    enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    X_tr[categorical] = enc.fit_transform(X_tr[categorical])
    X_te[categorical] = enc.transform(X_te[categorical])

    pos = y_tr.sum()
    neg = len(y_tr) - pos
    scale_pos_weight = (pos/neg) * 0.8

    clf = XGBClassifier(
        n_estimators=n_estimators,
        learning_rate=learning_rate,
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight,
        verbosity=0
    )
    clf.fit(X_tr, y_tr)

    proba = clf.predict_proba(X_te)[:,1]
    all_y.extend(y_te.tolist())
    all_proba.extend(proba.tolist())

# Threshold tuning
thresholds = np.linspace(0,1,101)
best_thresh, best_f1 = 0.5, 0.0
for thr in thresholds:
    preds = (np.array(all_proba) >= thr).astype(int)
    f1 = f1_score(all_y, preds, average='macro')
    if f1 > best_f1:
        best_f1, best_thresh = f1, thr

print(f"Best threshold for macro-F1: {best_thresh:.2f}")
print(f"Macro-F1 at best threshold: {best_f1:.3f}")

import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load & preprocess (drop rows missing the label)
train = (
    pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
      .dropna(subset=['pitch_type'])
      .copy()
)
test = (
    pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
      .dropna(subset=['pitch_type'])
      .copy()
)

# 2. Feature engineering
train['score_diff'] = train['bat_score'] - train['fld_score']
test ['score_diff'] = test ['bat_score'] - test ['fld_score']

def count_bucket(balls, strikes):
    if balls == 3 and strikes < 2:   return 'hitter'
    if strikes == 2 and balls < 3:   return 'pitcher'
    if balls == 3 and strikes == 2:  return 'full'
    return 'neutral'

for df in (train, test):
    df['count_bucket'] = df.apply(
        lambda r: count_bucket(r['balls'], r['strikes']), axis=1
    )

# 3. Select features & label
categorical = ['p_throws', 'stand', 'count_bucket']
numeric     = ['inning', 'outs_when_up', 'on_1b', 'on_2b', 'on_3b',
               'balls', 'strikes', 'score_diff']
features    = categorical + numeric

X_train = train[features].copy()
X_test  = test [features].copy()
y_train = train['pitch_type'].astype(str)
y_test  = test ['pitch_type'].astype(str)

# 4. Clean up the base-occupancy columns
for df in (X_train, X_test):
    df[['on_1b','on_2b','on_3b']] = (
        df[['on_1b','on_2b','on_3b']]
          .fillna(0)
          .astype(int)
    )

# 5. Encode categoricals
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train[categorical] = encoder.fit_transform(X_train[categorical])
X_test [categorical] = encoder.transform   (X_test [categorical])

# 6. Scale everything
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform   (X_test)

# 7. Train the SVM with a polynomial kernel
svm_poly = SVC(
    kernel='poly',               # polynomial kernel
    degree=3,                    # polynomial degree
    gamma='scale',               # kernel coefficient
    coef0=1.0,                   # independent term in kernel
    C=1.0,                       # regularization strength
    decision_function_shape='ovr',
    class_weight='balanced'
)
svm_poly.fit(X_train_scaled, y_train)

# 8. Evaluate
preds = svm_poly.predict(X_test_scaled)
print(f"Accuracy: {accuracy_score(y_test, preds):.4f}\n")
print("Classification Report:")
print(classification_report(y_test, preds))
print("Confusion Matrix:")
print(confusion_matrix(y_test, preds))

import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Load & drop rows missing the label
train = (
    pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
      .dropna(subset=['pitch_type'])
      .copy()
)
test = (
    pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')
      .dropna(subset=['pitch_type'])
      .copy()
)

# 2. Feature engineering: score differential
train['score_diff'] = train['bat_score'] - train['fld_score']
test ['score_diff'] = test ['bat_score'] - test ['fld_score']

# 3. Bucket the count
def count_bucket(balls, strikes):
    if balls == 3 and strikes < 2:   return 'hitter'
    if strikes == 2 and balls < 3:   return 'pitcher'
    if balls == 3 and strikes == 2:  return 'full'
    return 'neutral'

for df in (train, test):
    df['count_bucket'] = df.apply(
        lambda r: count_bucket(r['balls'], r['strikes']), axis=1
    )

# 4. Select features & labels
categorical = ['p_throws', 'stand', 'count_bucket']
numeric     = ['inning', 'outs_when_up', 'on_1b', 'on_2b', 'on_3b',
               'balls', 'strikes', 'score_diff']
features    = categorical + numeric

X_train = train[features].copy()
X_test  = test [features].copy()
y_train = train['pitch_type'].astype(str)
y_test  = test ['pitch_type'].astype(str)

# 5. Clean up base-occupancy: fill NaNs→0 and cast to int
for df in (X_train, X_test):
    df[['on_1b','on_2b','on_3b']] = (
        df[['on_1b','on_2b','on_3b']]
          .fillna(0)
          .astype(int)
    )

# 6. Encode categoricals with ordinal (or you can one-hot if you prefer)
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_train[categorical] = encoder.fit_transform(X_train[categorical])
X_test [categorical] = encoder.transform   (X_test [categorical])

# 7. Scale all features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform   (X_test)

# 8. Train a linear SVM
svm_lin = LinearSVC(
    C=1.0,
    class_weight='balanced',
    max_iter=10_000,
    dual=False        # set dual=False when n_samples > n_features
)
svm_lin.fit(X_train_scaled, y_train)

# 9. Evaluate
preds = svm_lin.predict(X_test_scaled)
print(f"Accuracy: {accuracy_score(y_test, preds):.4f}\n")
print("Classification Report:")
print(classification_report(y_test, preds))
print("Confusion Matrix:")
print(confusion_matrix(y_test, preds))

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# 1) Load your train/test sets
train = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_train.csv')
test  = pd.read_csv('/content/drive/MyDrive/baseball pitcher data DSMA/june_data_test.csv')

# 2) Feature engineering: count buckets & score differential
for df in (train, test):
    # count bucket
    df['count'] = df['balls'].astype(str) + '-' + df['strikes'].astype(str)
le_count = LabelEncoder()
le_count.fit(pd.concat([train['count'], test['count']]))
for df in (train, test):
    df['count_bucket'] = le_count.transform(df['count'])
    # score differential (bat_score minus fld_score)
    df['score_diff'] = df['bat_score'] - df['fld_score']

# 3) Encode categorical vars
# -- pitcher identifier
le_pitcher = LabelEncoder()
train['pitcher_id'] = le_pitcher.fit_transform(train['player_name'])
test['pitcher_id']  = le_pitcher.transform(test['player_name'])

# -- throwing hand & stance
le_throw = LabelEncoder()
le_stand = LabelEncoder()
train['p_throws_enc'] = le_throw.fit_transform(train['p_throws'])
test['p_throws_enc']  = le_throw.transform(test['p_throws'])
train['stand_enc']    = le_stand.fit_transform(train['stand'])
test['stand_enc']     = le_stand.transform(test['stand'])

# -- target
le_y = LabelEncoder()
train['y'] = le_y.fit_transform(train['pitch_type'])
test['y']  = le_y.transform(test['pitch_type'])

# 4) Auto-select all remaining features
to_exclude = {
    'player_name', 'p_throws', 'stand',
    'balls', 'strikes', 'bat_score', 'fld_score',
    'pitch_type', 'count', 'y'
}
features = [c for c in train.columns if c not in to_exclude]

# 5) Train per-pitcher RandomForest and XGBoost models
rf_models, xgb_models = {}, {}
y_true_rf,  y_pred_rf  = [], []
y_true_xgb, y_pred_xgb = [], []

for pid in train['pitcher_id'].unique():
    tr_mask = train['pitcher_id'] == pid
    te_mask = test ['pitcher_id'] == pid

    X_tr, y_tr = train.loc[tr_mask, features], train.loc[tr_mask, 'y']
    X_te, y_te = test .loc[te_mask, features],  test .loc[te_mask, 'y']

    if len(y_tr) < 20 or X_te.empty:
        continue

    # Random Forest (no change)
    rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    rf.fit(X_tr, y_tr)
    # …

    # XGBoost with built-in encoding
    xgb = XGBClassifier(
        eval_metric='mlogloss',
        random_state=42,
        n_jobs=-1
    )
    xgb.fit(X_tr, y_tr)

    y_pred_xgb.extend(xgb.predict(X_te))
    y_true_xgb.extend(y_te)

    # XGBoost
    xgb = XGBClassifier(
        use_label_encoder=False,
        eval_metric='mlogloss',
        random_state=42,
        n_jobs=-1
    )
    xgb.fit(X_tr, y_tr)
    xgb_models[pid] = xgb
    y_pred_xgb.extend(xgb.predict(X_te))
    y_true_xgb.extend(y_te)

# 6) Evaluate overall accuracy
print(f"Random Forest overall accuracy: {accuracy_score(y_true_rf, y_pred_rf):.3f}")
print(f"XGBoost overall accuracy:       {accuracy_score(y_true_xgb, y_pred_xgb):.3f}")